# Generated by Django 3.1.3 on 2025-07-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_medreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medreport',
            name='conf_score',
            field=models.FloatField(blank=True, default=0, max_length=5, verbose_name='Confidence Score'),
            preserve_default=False,
        ),
    ]
